name: Build
on:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - name: feedbin-web
            context: .
            build-args: FEEDBIN_REPO=https://github.com/AndreasSko/feedbin.git
    
          - name: feedbin-extract
            context: feedbin-extract

          - name: feedbin-image
            context: feedbin-image

          - name: feedbin-refresher
            context: feedbin-refresher

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.2.2
        with:
          context: ${{ matrix.image.context }}
          push: true
          build-args: ${{ matrix.image.build-args }}
          tags: andreassko/${{ matrix.image.name }}
